<strong>Project</strong>: fabric-sdk-node<br><strong>Branch</strong>: master<br><strong>ID</strong>: 27676<br><strong>Subject</strong>: FABN-926: Improve messages for failed proposals<br><strong>Status</strong>: MERGED<br><strong>Owner</strong>: Mark S. Lewis - Mark.S.Lewis@outlook.com<br><strong>Assignee</strong>:<br><strong>Created</strong>: 11/20/2018, 2:44:08 PM<br><strong>LastUpdated</strong>: 11/21/2018, 8:57:48 AM<br><strong>CommitMessage</strong>:<br><pre>FABN-926: Improve messages for failed proposals

- Make the thrown error message from fabric-network API for concise.
- Log full error received from fabric-client API.

Change-Id: I05c8454a8a2291580b61db068160abfb50824c59
Signed-off-by: Mark S. Lewis <mark_lewis@uk.ibm.com>
</pre><h1>Comments</h1><strong>Reviewer</strong>: Mark S. Lewis - Mark.S.Lewis@outlook.com<br><strong>Reviewed</strong>: 11/20/2018, 2:44:08 PM<br><strong>Message</strong>: <pre>Uploaded patch set 1.</pre><strong>Reviewer</strong>: Hyperledger Jobbuilder - jobbuilder@jenkins.hyperledger.org<br><strong>Reviewed</strong>: 11/20/2018, 2:44:16 PM<br><strong>Message</strong>: <pre>Patch Set 1:

Build Started https://jenkins.hyperledger.org/job/fabric-sdk-node-verify-s390x/213/ (2/2)</pre><strong>Reviewer</strong>: Hyperledger Jobbuilder - jobbuilder@jenkins.hyperledger.org<br><strong>Reviewed</strong>: 11/20/2018, 2:44:16 PM<br><strong>Message</strong>: <pre>Patch Set 1:

Build Started https://jenkins.hyperledger.org/job/fabric-sdk-node-verify-x86_64/1579/ (1/2)</pre><strong>Reviewer</strong>: Hyperledger Jobbuilder - jobbuilder@jenkins.hyperledger.org<br><strong>Reviewed</strong>: 11/20/2018, 3:10:53 PM<br><strong>Message</strong>: <pre>Patch Set 1: Verified-1

Build Failed 

https://jenkins.hyperledger.org/job/fabric-sdk-node-verify-s390x/213/ : FAILURE

Logs: https://logs.hyperledger.org/production/vex-yul-hyp-jenkins-3/fabric-sdk-node-verify-s390x/213

https://jenkins.hyperledger.org/job/fabric-sdk-node-verify-x86_64/1579/ : SUCCESS

Logs: https://logs.hyperledger.org/production/vex-yul-hyp-jenkins-3/fabric-sdk-node-verify-x86_64/1579</pre><strong>Reviewer</strong>: Mark S. Lewis - Mark.S.Lewis@outlook.com<br><strong>Reviewed</strong>: 11/21/2018, 3:51:41 AM<br><strong>Message</strong>: <pre>Patch Set 1:

reverify-node8z</pre><strong>Reviewer</strong>: Mark S. Lewis - Mark.S.Lewis@outlook.com<br><strong>Reviewed</strong>: 11/21/2018, 3:51:49 AM<br><strong>Message</strong>: <pre>Patch Set 1:

reverify-z</pre><strong>Reviewer</strong>: Hyperledger Jobbuilder - jobbuilder@jenkins.hyperledger.org<br><strong>Reviewed</strong>: 11/21/2018, 3:51:57 AM<br><strong>Message</strong>: <pre>Patch Set 1: -Verified

Build Started https://jenkins.hyperledger.org/job/fabric-sdk-node-verify-s390x/216/</pre><strong>Reviewer</strong>: Hyperledger Jobbuilder - jobbuilder@jenkins.hyperledger.org<br><strong>Reviewed</strong>: 11/21/2018, 4:17:29 AM<br><strong>Message</strong>: <pre>Patch Set 1: Verified-1

Build Failed 

https://jenkins.hyperledger.org/job/fabric-sdk-node-verify-s390x/216/ : FAILURE

Logs: https://logs.hyperledger.org/production/vex-yul-hyp-jenkins-3/fabric-sdk-node-verify-s390x/216</pre><strong>Reviewer</strong>: Mark S. Lewis - Mark.S.Lewis@outlook.com<br><strong>Reviewed</strong>: 11/21/2018, 5:04:54 AM<br><strong>Message</strong>: <pre>Patch Set 1:

reverify-z</pre><strong>Reviewer</strong>: Hyperledger Jobbuilder - jobbuilder@jenkins.hyperledger.org<br><strong>Reviewed</strong>: 11/21/2018, 5:05:06 AM<br><strong>Message</strong>: <pre>Patch Set 1: -Verified

Build Started https://jenkins.hyperledger.org/job/fabric-sdk-node-verify-s390x/217/</pre><strong>Reviewer</strong>: Mark S. Lewis - Mark.S.Lewis@outlook.com<br><strong>Reviewed</strong>: 11/21/2018, 5:18:23 AM<br><strong>Message</strong>: <pre>Patch Set 1:

Prior to this change, the error message returned from submitTransaction() in the e2e error handling test was:
# No valid responses from any peers.
# Response from attempted peer comms was an error: {"message":"transaction returned with failure: Error: throwError: an error occurred","stack":"Error: transaction returned with failure: Error: throwError: an error occurred\n    at self._endorserClient.processProposal (/Users/mark/gerrit.hyperledger.org/fabric-sdk-node/fabric-client/lib/Peer.js:47:462)\n    at Object.onReceiveStatus (/Users/mark/gerrit.hyperledger.org/fabric-sdk-node/node_modules/grpc/src/client_interceptors.js:1191:9)\n    at InterceptingListener._callNext (/Users/mark/gerrit.hyperledger.org/fabric-sdk-node/node_modules/grpc/src/client_interceptors.js:564:42)\n    at InterceptingListener.onReceiveStatus (/Users/mark/gerrit.hyperledger.org/fabric-sdk-node/node_modules/grpc/src/client_interceptors.js:614:8)\n    at callback (/Users/mark/gerrit.hyperledger.org/fabric-sdk-node/node_modules/grpc/src/client_interceptors.js:841:24)","status":500,"payload":{"type":"Buffer","data":[]},"isProposalResponse":true}
# Response from attempted peer comms was an error: {"message":"transaction returned with failure: Error: throwError: an error occurred","stack":"Error: transaction returned with failure: Error: throwError: an error occurred\n    at self._endorserClient.processProposal (/Users/mark/gerrit.hyperledger.org/fabric-sdk-node/fabric-client/lib/Peer.js:47:462)\n    at Object.onReceiveStatus (/Users/mark/gerrit.hyperledger.org/fabric-sdk-node/node_modules/grpc/src/client_interceptors.js:1191:9)\n    at InterceptingListener._callNext (/Users/mark/gerrit.hyperledger.org/fabric-sdk-node/node_modules/grpc/src/client_interceptors.js:564:42)\n    at InterceptingListener.onReceiveStatus (/Users/mark/gerrit.hyperledger.org/fabric-sdk-node/node_modules/grpc/src/client_interceptors.js:614:8)\n    at callback (/Users/mark/gerrit.hyperledger.org/fabric-sdk-node/node_modules/grpc/src/client_interceptors.js:841:24)","status":500,"payload":{"type":"Buffer","data":[]},"isProposalResponse":true}

After this change, the error message from the same test is:
# No valid responses from any peers. 2 peer error responses:
# transaction returned with failure: Error: throwError: an error occurred
# transaction returned with failure: Error: throwError: an error occurred

The underlying error is logged as a warning so no information is lost.</pre><strong>Reviewer</strong>: Hyperledger Jobbuilder - jobbuilder@jenkins.hyperledger.org<br><strong>Reviewed</strong>: 11/21/2018, 5:31:05 AM<br><strong>Message</strong>: <pre>Patch Set 1: Verified+1

Build Successful 

https://jenkins.hyperledger.org/job/fabric-sdk-node-verify-s390x/217/ : SUCCESS

Logs: https://logs.hyperledger.org/production/vex-yul-hyp-jenkins-3/fabric-sdk-node-verify-s390x/217</pre><strong>Reviewer</strong>: Andrew Coleman - andrew_coleman@uk.ibm.com<br><strong>Reviewed</strong>: 11/21/2018, 8:28:25 AM<br><strong>Message</strong>: <pre>Patch Set 1: Code-Review+2</pre><strong>Reviewer</strong>: Andrew Coleman - andrew_coleman@uk.ibm.com<br><strong>Reviewed</strong>: 11/21/2018, 8:28:28 AM<br><strong>Message</strong>: <pre>Change has been successfully merged by Andrew Coleman</pre><strong>Reviewer</strong>: Hyperledger Jobbuilder - jobbuilder@jenkins.hyperledger.org<br><strong>Reviewed</strong>: 11/21/2018, 8:57:48 AM<br><strong>Message</strong>: <pre>Patch Set 1:

Build Failed 

https://jenkins.hyperledger.org/job/fabric-sdk-node-merge-x86_64/74/ : FAILURE

Logs: https://logs.hyperledger.org/production/vex-yul-hyp-jenkins-3/fabric-sdk-node-merge-x86_64/74

https://jenkins.hyperledger.org/job/fabric-sdk-node-merge-s390x/62/ : FAILURE

Logs: https://logs.hyperledger.org/production/vex-yul-hyp-jenkins-3/fabric-sdk-node-merge-s390x/62</pre><h1>PatchSets</h1><h3>PatchSet Number: 1</h3><blockquote><strong>Type</strong>: REWORK<br><strong>Author</strong>: Mark S. Lewis - mark_lewis@uk.ibm.com<br><strong>Uploader</strong>: Mark S. Lewis - Mark.S.Lewis@outlook.com<br><strong>Created</strong>: 11/20/2018, 2:44:08 PM<br><strong>GitHubMergedRevision</strong>: [2068039819fb98634f20bb35098642763a6fbfb0](https://github.com/hyperledger/fabric-sdk-node/commit/2068039819fb98634f20bb35098642763a6fbfb0)<br><br><strong>Approver</strong>: Hyperledger Jobbuilder - jobbuilder@jenkins.hyperledger.org<br><strong>Approved</strong>: 11/21/2018, 5:31:05 AM<br><strong>Type</strong>: Verified<br><strong>Value</strong>: 1<br><br><strong>Approver</strong>: Andrew Coleman - andrew_coleman@uk.ibm.com<br><strong>Approved</strong>: 11/21/2018, 8:28:25 AM<br><strong>Type</strong>: Code-Review<br><strong>Value</strong>: 1<br><br><strong>MergedBy</strong>: Andrew Coleman<br><strong>Merged</strong>: 11/21/2018, 8:28:28 AM<br><br></blockquote>